{
  final Iterable<RecoverableException> appEx=Iterables.filter(Throwables.getCausalChain(ex),RecoverableException.class);
  final Iterator<RecoverableException> iterator=appEx.iterator();
  return iterator.hasNext() ? iterator.next() : null;
}
