{
  ersGeneral=new ExceptionRecognizerGeneral(Predicates.<Throwable>alwaysTrue(),prepend);
  assertThat(ersGeneral.recognize(new FooException()),is("pre: foo"));
}
