{
  try {
    super.handle(event);
  }
 catch (  final Exception exception) {
    processException(exception,event);
  }
}
