{
  try {
    set.verify();
  }
 catch (  AssertionFailedError e) {
    return;
  }
  fail();
}
