{
  ersGeneral=new ExceptionRecognizerGeneral(Predicates.<Throwable>alwaysFalse());
  assertThat(ersGeneral.recognize(new FooException()),is(nullValue()));
}
