{
  ersGeneral=new ExceptionRecognizerAbstract(Predicates.<Throwable>alwaysFalse()){
  }
;
  assertThat(ersGeneral.recognize(new FooException()),is(nullValue()));
}
