{
  custJsDO.disablePlaceOrder="cannot invoke";
  try {
    custJsWO.placeOrder(product355DO,3);
    fail("Should have thrown exception");
  }
 catch (  final DisabledException ex) {
    assertThat(ex.getAdvisorClass(),classEqualTo(DisableForContextFacetViaMethod.class));
    assertThat(ex.getIdentifier().getMemberNaturalName(),equalTo("Place Order"));
    assertThat(ex.getMessage(),Matchers.containsString("cannot invoke"));
  }
}
