{
  LOG.info("Exception executing " + getName() + ", aborting transaction");
  try {
    objectManager.abortTransaction();
  }
 catch (  Exception e2) {
    ExceptionHelper.log(OneToOneTransaction.class,"Failure during abort",e2);
  }
}
