{
  LOG.info("Exception executing " + getName() + ", aborting transaction");
  try {
    objectManager.abortTransaction();
  }
 catch (  Exception e2) {
    LOG.error("Failure during abort",e2);
  }
}
