{
  ex=new RecognizedException("foo");
  assertThat(container.recognize(ex),is(not(nullValue())));
}
